### ISSUE TITLE
Save the open/close state as an attribute in editor and front-end

### ISSUE THREAD

**Issue by NewJenk** [mrwweb/mrw-accordion#39]
Really nice accordion! I've tested a load of Gutenberg accordion blocks and this is by far the best.

It would be great if the open/close state was saved as an attribute, and the attribute used on the front-end and edit screen on initial page load. So as an example, if an editor sets the accordion as closed on the edit screen, the accordion would be closed both on the edit screen and on the front-end by default.

**Comment by mrwweb** [comment]
@NewJenk Thanks for the kind words and feedback. I appreciate you opening the request. I'll share some thoughts and please respond if you have more to add.

I have no doubt that you're not the only person who wants the ability to have an accordion open-by-default, but I've been hesitant to add it based on both my own experience and chatting with other users. I tend to take the view that if it's open by default, then it doesn't need to be in a collapsible widget. I'm not convinced to change my mind yet, but I won't close this issue immediately either.

The thing that I have noticed while editing is that I really wish the accordions could load closed by default in the editor. It may be sufficient to always load them closed by default, but I do wonder about whether it makes more sense to save the _editor state_ as an attribute on the block that only impacts the editor view. Would this be a valuable half-measure for you, or is that not really the point?

I'll note that if I were to add a "open by default" option, I think it would probably go in the settings sidebar so that the editor's open/close state is independent of the front-end default.
